### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by hugomesquita-dev** [Harievilozanini/mercadopagotransparente#1]
Olá, alterei todas as configurações de token e key para o meu.
Mas não funcionou. Deu o seguinte erro

Warning: Illegal string offset 'code' in /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php on line 524

Warning: Illegal string offset 'description' in /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php on line 524

Fatal error: Uncaught exception 'MercadoPagoException' with message 'Invalid users involved - : - I: I - : ' in /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php:533 Stack trace: #0 /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php(562): MPRestClient::exec(Array) #1 /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php(356): MPRestClient::post(Array) #2 /home/hugomesquita/public_html/mercadopago/post_payment.php(64): MP->post('/v1/payments/', Array) #3 {main} thrown in /home/hugomesquita/public_html/mercadopago/lib/mercadopago.php on line 533

**Comment by M3ndes** [comment]
Boa tarde, mudei as configurações como explicado, entretanto ao clicar no botão de pagar o erro "verify filled data aparece" o que pode ser?

**Comment by hugomesquita-dev** [comment]
@M3ndes é porque não foi estabelecida o status de conexão, não foi iniciado ou gerado o token_session, dar um refrash na página e preenche os campos manualmente e envia. 
Você pode verificar isso na linha [152](https://github.com/Harievilozanini/mercadopagotransparente/blob/fa2580ffa4ce3cb10a7808da52faa9650ab5f5f8/index.php#L153) do arquivo index.php

**Comment by M3ndes** [comment]
Já consegui realizar a compra, mas só consigo acessar os dados da transação copiando e colando o id da compra na url. 
Quais são os procedimentos para configuração o campo notification_url? Não nada sobre isso no projeto.

**Comment by luizcarlospedrosogomes** [comment]
https://www.mercadopago.com/mlb/account/webhooks

se isto estiver configurado o mercado pago envia um get para url de notificacao

**Comment by hugomesquita-dev** [comment]
RESOLVED
